Task_2_2_1
izm-ka/OOP pull request #12
Opened 2024-03-06 07:04 UTC by izm-ka

2024-03-15 07:54 UTC, BIGNIKi requested changes

2024-03-15 07:54 UTC, BIGNIKi commented on Task_2_2_1/.gitignore
> +.gradle
Все json сгруппировать в пакет и интерфейсы, Main вытащить на пакет выше

2024-03-15 07:54 UTC, BIGNIKi commented on Task_2_2_1/src/main/java/ru/nsu/izmailova/pizzeria/JsonPizzeria.java
> +    private final int storageSize;
Не используется, надо доделать

2024-03-15 07:54 UTC, BIGNIKi commented on Task_2_2_1/src/main/java/ru/nsu/izmailova/pizzeria/Baker.java
> +package ru.nsu.izmailova.pizzeria;
Добавить логику сериализации заказов, которые не доделали и при очередном запуске пиццерии их надо обработать первыми.

2024-03-19 06:28 UTC, BIGNIKi requested changes

2024-03-19 06:28 UTC, BIGNIKi commented on Task_2_2_1/src/main/java/ru/nsu/izmailova/pizzeria/Consumer.java
> +public interface Consumer extends Runnable {
Вынеси все интерфейсы в отдельный пакет. 
Можно еще там по какой-то логике все сгруппировать. Сейчас там помойка - всё в одном пакете

2024-03-19 06:28 UTC, BIGNIKi commented on Task_2_2_1/src/main/java/ru/nsu/izmailova/pizzeria/JsonBaker.java
> +    private int cookingTime;
Модификторы final забываешь применять. Лучше их использовать везде, где это возможно

2024-03-19 06:28 UTC, BIGNIKi commented on Task_2_2_1/src/main/java/ru/nsu/izmailova/pizzeria/JsonBaker.java
> +public class JsonBaker {
Всё связанное с json в отдельный пакет

2024-03-19 06:28 UTC, BIGNIKi commented on Task_2_2_1/src/main/java/ru/nsu/izmailova/pizzeria/Baker.java
> +    public void changeProcessingTime(int time) {
changeProcessingTime есть и в Baker, и в Customer и они оба реализуют контракт Producer, так почему в интерфейсе нет changeProcessingTime?

2024-03-19 06:28 UTC, BIGNIKi commented on Task_2_2_1/src/main/java/ru/nsu/izmailova/pizzeria/Pizzeria.java
> +    private final Customer customers;
Раз уже пишем код на уровне интерфейсов, давай тип переменной будет типо интерфейса: Producer
И плюс,: Producer и Consumer лучше переименовать, добавив приставку I, чтобы сразу было понятно, что это интерфейс. Будет у тебя IProducer и IConsumer. В Java так обычно не делают (не знаю почему), но таким образом, как по мне, куда проще понять, что сущность является интерфейсом

2024-03-19 06:28 UTC, BIGNIKi commented on Task_2_2_1/src/main/java/ru/nsu/izmailova/pizzeria/DataQueue.java
> +public class DataQueue {
Для очереди тоже можно сочинить интерфейс, чтобы писать код на уровне абстракции

2024-03-19 06:28 UTC, BIGNIKi commented on Task_2_2_1/src/main/java/ru/nsu/izmailova/pizzeria/Pizzeria.java
> +    private final List<DeliveryGuy> deliverers;
Здесь как-будто бы тоже можно уйти на уровень абстракции: List<Consumer>

2024-03-19 06:28 UTC, BIGNIKi commented on Task_2_2_1/src/main/java/ru/nsu/izmailova/pizzeria/Baker.java
> +public class Baker implements Consumer, Producer {
Для Baker`а можно сделать абстрактный класс, объединяющий поведение Consumer и Producer, чтобы в Pizzeria также использовала этот абстрактный класс

2024-03-19 06:28 UTC, BIGNIKi commented on Task_2_2_1/src/main/java/ru/nsu/izmailova/pizzeria/Baker.java
> +        System.out.println("Order[" + deliveryCounter + "] is " + orderConsumeStatus);
Для логгирования примени log4j

2024-03-19 06:28 UTC, BIGNIKi commented on Task_2_2_1/src/main/java/ru/nsu/izmailova/pizzeria/Pizzeria.java
> +        Thread.sleep(30 * 1000);
Зачем эти ожидания? Если это попытка синхронизировать выполнение потоков, то так делать нельзя

2024-03-19 06:28 UTC, BIGNIKi commented on Task_2_2_1/src/test/java/ru/nsu/izmailova/pizzeria/BakerTest.java
> +public class BakerTest {
Тестов на пиццерию, Customer, Json`ы нет

2024-03-19 06:28 UTC, BIGNIKi commented on Task_2_2_1/src/test/java/ru/nsu/izmailova/pizzeria/BakerTest.java
> +package ru.nsu.izmailova.pizzeria;
Еще нужна класс-диаграмма

2024-03-19 06:47 UTC, izm-ka commented on Task_2_2_1/src/test/java/ru/nsu/izmailova/pizzeria/BakerTest.java
> +package ru.nsu.izmailova.pizzeria;
https://github.com/izm-ka/OOP/blob/Task_2_2_1/Task_2_2_1.png

2024-03-19 06:50 UTC, BIGNIKi commented on Task_2_2_1/src/test/java/ru/nsu/izmailova/pizzeria/BakerTest.java
> +package ru.nsu.izmailova.pizzeria;
В папку с задачей положи лучше

2024-03-19 06:53 UTC, izm-ka commented on Task_2_2_1/src/main/java/ru/nsu/izmailova/pizzeria/Pizzeria.java
> +        Thread.sleep(30 * 1000);
Thread.sleep(15 * 1000); - имитация времени, за которое все заказы должны обработаться после того как посетители перестали делать заказы
Thread.sleep(30 * 1000); - имитация времени, за которое пекари должны успеть закончить свою работу
ну это все равно надо будет переделывать, мы это на прошлой паре обсуждали

2024-04-03 05:54 UTC, BIGNIKi approved these changes

2024-04-03 05:55 UTC, merged