Task_1_4_1
izm-ka/OOP pull request #7
Opened 2023-11-26 09:06 UTC by izm-ka

2023-11-28 08:37 UTC, shadrina requested changes
Мы договаривались, что перед запросом на ревью вы смотрите вкладку Files changed на наличие варнингов от reviewdog. Если они есть, я могу даже не смотреть код.

2023-11-28 08:37 UTC, shadrina commented on Task_1_4_1/src/test/java/ru/nsu/izmailova/gradebook/GradebookTest.java
> +    public void average_test() {
Нейминг не по style guide. В Java используем только camelCase.

2023-11-28 08:37 UTC, shadrina commented on Task_1_4_1/src/main/java/ru/nsu/izmailova/gradebook/Gradebook.java
> +        return scholarship() && cnt < 3;
Stream API please

2023-11-28 08:37 UTC, shadrina commented on Task_1_4_1/src/main/java/ru/nsu/izmailova/gradebook/Gradebook.java
> +        return true;
Stream API please

2023-11-28 08:37 UTC, shadrina commented on Task_1_4_1/src/main/java/ru/nsu/izmailova/gradebook/Gradebook.java
> +        return qualifTask == Marks.Excellent;
1 return + Stream API please

2023-11-28 08:37 UTC, shadrina commented on Task_1_4_1/src/main/java/ru/nsu/izmailova/gradebook/Gradebook.java
> +        return avg / cnt;
1 return + Stream API please

2023-11-28 08:37 UTC, shadrina commented on Task_1_4_1/src/main/java/ru/nsu/izmailova/gradebook/Gradebook.java
> +public class Gradebook {
Как учитываются пересдачи?

2023-11-28 11:15 UTC, izm-ka commented on Task_1_4_1/src/main/java/ru/nsu/izmailova/gradebook/Gradebook.java
> +public class Gradebook {
в scholarship() если оценка 3 или 2, то студент теряет стипендию

2023-11-28 11:55 UTC, shadrina commented on Task_1_4_1/src/main/java/ru/nsu/izmailova/gradebook/Gradebook.java
> +public class Gradebook {
А если пересдали на 4/5, это будет еще одна оценка?

2023-11-28 12:16 UTC, izm-ka commented on Task_1_4_1/src/main/java/ru/nsu/izmailova/gradebook/Gradebook.java
> +public class Gradebook {
поняла, спасибо

2023-11-28 16:51 UTC, izm-ka reviewed
учитываю пересдачу только при подсчете стипендии, вы вроде на почте сказали этого достаточно
поняла, что нужно изменить процесс добавления оценки, чтобы при пересдаче последнее значение перезаписывалось, а не добавлялось новое. Но сделать не успела

2023-12-05 04:12 UTC, shadrina approved these changes

2023-12-06 14:09 UTC, merged