Task_1_5_1
izm-ka/OOP pull request #8
Opened 2023-12-04 11:33 UTC by izm-ka

2023-12-05 11:19 UTC, shadrina requested changes

2023-12-05 11:19 UTC, shadrina commented on Task_1_5_1/src/main/java/ru/nsu/izmailova/calculator/Calculator.java
> +    Stack<Double> result = new Stack<>();
Вместо старенького синхронизованного `java.util.Stack` я рекомендую пользоваться `java.util.Deque` с аналогичным API для стека.

2023-12-05 11:19 UTC, shadrina commented on Task_1_5_1/src/main/java/ru/nsu/izmailova/calculator/Calculator.java
> +    List<String> expression;
Для софта ОК, но по-хорошему хотелось бы перед самой калькуляцией считывать выражение не в список строк, а в список из объектов своей внутренней структуры, например, `List<Token>`, где `Token` может быть либо операцией, либо числом.

2023-12-05 11:19 UTC, shadrina commented on Task_1_5_1/src/main/java/ru/nsu/izmailova/calculator/Calculator.java
> +                        throw new Exception("Incorrect input");
В этой задаче нужно грамотно обрабатывать разные исключительные ситуации. Так, чтобы при очередной ошибке не падало все приложение (как это сейчас), а, например, выводилось сообщение в System.out или System.err с соответствующим сообщением. Вам нужно позаботиться о понятном поведении для пользователя. Я не ожидаю, что калькулятор упадет, если я поделю на 0 или ошибусь в написании)

2023-12-05 11:21 UTC, shadrina commented on Task_1_5_1/src/main/java/ru/nsu/izmailova/calculator/Calculator.java
> +                        throw new Exception("Incorrect input");
Хотя сейчас оно не падает, вру. В любом случае, этот момент постарайся оформить более элегантно.

2023-12-05 11:22 UTC, izm-ka commented on Task_1_5_1/src/main/java/ru/nsu/izmailova/calculator/Calculator.java
> +    List<String> expression;
типа через LinkedList?

2023-12-05 11:24 UTC, izm-ka commented on Task_1_5_1/src/main/java/ru/nsu/izmailova/calculator/Calculator.java
> +                        throw new Exception("Incorrect input");
![image](https://github.com/izm-ka/OOP/assets/73380467/b334ad28-23cd-4b09-b7dc-6b9c1f1291a8)
при исключительных ситуациях у меня выводится ошибка и запрашивается новое выражение на вход

2023-12-12 08:48 UTC, shadrina requested changes

2023-12-12 08:48 UTC, shadrina commented on Task_1_5_1/src/main/java/ru/nsu/izmailova/calculator/Calculator.java
> +    List<String> expression;
Нет. Какая реализация списка используется - неважно. 
Я имела в виду собственный класс `Token`, вместо используемого `String`, где `Token` -- это либо операция, либо число.

2023-12-12 08:48 UTC, shadrina commented on Task_1_5_1/src/main/java/ru/nsu/izmailova/calculator/Calculator.java
> +                case ("+"):
Тогда вот это будет не switch по строкам, а switch по токенам

2023-12-12 08:48 UTC, shadrina commented on Task_1_5_1/src/main/java/ru/nsu/izmailova/calculator/Main.java
> +                if (expression.get(0).equals("q")) {
А если пользователь введет пустую строку?

2023-12-12 08:48 UTC, shadrina commented on Task_1_5_1/src/test/java/ru/nsu/izmailova/calculator/CalculatorTest.java
> +        Calculator exp = new Calculator(Arrays.asList("pow", "2", "3"));
Сделай конструктор, который принимает просто строку. Так не очень удобно и наглядно.

2023-12-12 15:54 UTC, izm-ka commented on Task_1_5_1/src/main/java/ru/nsu/izmailova/calculator/Calculator.java
> +                case ("+"):
ага, понятно
вы просто в прошлый раз написали, что в целом ок, поэтому я из-за нехватки времени не стала эту часть менять
создала просто массив строк tokens

2023-12-12 15:56 UTC, izm-ka commented
только у меня появилась какая-то проблема с делением, хотя вроде все ок..
тест Assertions.assertEquals("Division by zero is not allowed", thrown.getMessage()); проходит, но в консоль выводится null, а не 
Division by zero is not allowed

2023-12-18 09:53 UTC, shadrina commented
Оно должно полностью падать при делении на ноль, верно? Отладь, расскажи, почему так происходит. Тогда засчитаю в срок.

2023-12-18 09:55 UTC, shadrina reviewed
Засчитаю, если будет выполнено задание выше. Так-то, конечно, я хотела более замысловатое решение, о чем писала еще с софта.

2024-02-05 14:25 UTC, closed without merging